### PR TITLE
Improve README

### PR DESCRIPTION
**Pull request by ValueRaider**
@kschmid I will improve README to answer your questions. If you still have questions, throw them at me.

### CODE REVIEW

**Review by kschmid — APPROVED** [review]
Not sure, why this pops up as to approve, for me. 
Only improvement suggestion: regarding the caches: is this fixed or can one modify the location just as with the session_caches. Just a comment like (currently location-change not possible).

**Review by kschmid — APPROVED** [review]

**Review by kschmid — APPROVED** [review]

**Comment by ValueRaider** [comment]
I tagged you because you seemed confused how this  caching worked.

**Comment by ValueRaider** [comment]
I can allow changing cache location, like with yfinance.

**Comment by kschmid** [comment]
yeah, was a bit confused with how it works with yfinance_cache, but also with caching in general. (Very new to the python ecosystem)
I found the possibility to move caches around rather helpful. In particular while experimenting. 
(And I am personally not a fan of software which simply puts large junks of data somewhere. )

**Comment by ValueRaider** [comment]
> And I am personally not a fan of software which simply puts large junks of data somewhere.

What I do is normal, and cache must go somewhere. Many programs on Linux dump data in the same folder as YFC, and some more than YFC e.g. PIP's cache. Can't speak for Mac but probably same - maybe you should look.

**Pull request merged**
